# Spring properties
spring:
  application:
     name: service-gateway

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 1111   # HTTP (Tomcat) port
  
  
rabbitmq:
    addresses: ${vcap.services.${PREFIX:}rabbitmq.credentials.uri:amqp://${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}}
    
hystrix:
  command:
    default:
      circuitBreaker: requestVolumeThreshold:5
      